// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwawFdr9-mYgtTUKCqS5A4bmlkSx-90J4',
    appId: '1:16558702031:web:d9b21702dcf1c9d3b066ba',
    messagingSenderId: '16558702031',
    projectId: 'voluntracker',
    authDomain: 'voluntracker.firebaseapp.com',
    storageBucket: 'voluntracker.appspot.com',
    measurementId: 'G-TNQ0PFHS5W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZ1RuZbeBcz6FKmEOTVML6cZfbQHBkjeo',
    appId: '1:16558702031:android:c3c081c9028b53d5b066ba',
    messagingSenderId: '16558702031',
    projectId: 'voluntracker',
    storageBucket: 'voluntracker.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAawJ4vWL42phpodoE9R2hMTQTazRRzi1E',
    appId: '1:16558702031:ios:bdc54599f7e5a966b066ba',
    messagingSenderId: '16558702031',
    projectId: 'voluntracker',
    storageBucket: 'voluntracker.appspot.com',
    iosClientId: '16558702031-u5nr1hjhplnaa3kfsbh1t8pm28klo7m4.apps.googleusercontent.com',
    iosBundleId: 'app.voluntracker.voluntracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAawJ4vWL42phpodoE9R2hMTQTazRRzi1E',
    appId: '1:16558702031:ios:bdc54599f7e5a966b066ba',
    messagingSenderId: '16558702031',
    projectId: 'voluntracker',
    storageBucket: 'voluntracker.appspot.com',
    iosClientId: '16558702031-u5nr1hjhplnaa3kfsbh1t8pm28klo7m4.apps.googleusercontent.com',
    iosBundleId: 'app.voluntracker.voluntracker',
  );
}
